#!/usr/bin/env python3
"""Generate ISA tables from spec/isa.json.

Outputs:
  pysim8/src/pysim8/_isa_tables.py
  web/lib/_isa_tables.js
  vscode-sim8/syntaxes/sim8asm.tmLanguage.json  (mnemonic patterns only)

Run from any directory:
  python isa/codegen.py
  python isa/codegen.py --check   # verify outputs are up to date
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_REPO = Path(__file__).parent.parent
_JSON = _REPO / "spec/isa.json"

_PY_OUT = _REPO / "pysim8/src/pysim8/_isa_tables.py"
_JS_OUT = _REPO / "web/lib/_isa_tables.js"
_VSCODE_OUT = _REPO / "vscode-sim8/syntaxes/sim8asm.tmLanguage.json"

# ── operand type byte sizes (mirrors OpType._OPTYPE_BYTES in isa.py) ─────────

_OP_BYTES: dict[str, int] = {"fp_imm16": 2}


def _instr_size(operands: list[str]) -> int:
    return 1 + sum(_OP_BYTES.get(o, 1) for o in operands)


# ── Shared helpers ────────────────────────────────────────────────────────────


def _repr_list(lst: list[str]) -> str:
    if not lst:
        return "[]"
    items = ", ".join(f'"{s}"' for s in lst)
    return f"[{items}]"


# ── Python generator ──────────────────────────────────────────────────────────


def _gen_py(isa: dict) -> str:
    lines: list[str] = []
    a = lines.append

    a("# AUTO-GENERATED by isa/codegen.py — do not edit directly.")
    a("# Source of truth: spec/isa.json")
    a("")
    a("from __future__ import annotations")
    a("")
    a("from enum import IntEnum")
    a("")
    a("")

    # Op enum
    a("class Op(IntEnum):")
    a('    """CPU opcodes (decimal values from spec/isa.json)."""')
    a("")

    groups = [
        ("Core (0–97)", isa["instructions"]),
        ("FP (128–162)", isa["instructions_fp"]),
        ("VU (163–183)", isa["instructions_vu"]),
    ]
    for group_label, instrs in groups:
        a(f"    # {group_label}")
        for instr in instrs:
            a(f"    {instr['op']} = {instr['opcode']}")
        a("")

    # ISA_DATA
    a("")
    a("# ── Instruction data ─────────────────────────────────────────────────")
    a("# Each entry: (op_name, opcode, mnemonic, operands, cost, format_dep)")
    a("")

    for var, key in [
        ("ISA_DATA", "instructions"),
        ("ISA_FP_DATA", "instructions_fp"),
        ("ISA_VU_DATA", "instructions_vu"),
    ]:
        a(f"{var}: list[tuple[str, int, str, list[str], int, bool]] = [")
        for instr in isa[key]:
            fd = str(instr.get("format_dep", False))
            ops = _repr_list(instr["operands"])
            a(f'    ("{instr["op"]}", {instr["opcode"]}, "{instr["mnemonic"]}", {ops}, {instr["cost"]}, {fd}),')
        a("]")
        a("")

    # FP_REG_DATA
    a("# ── FP register data ─────────────────────────────────────────────────")
    a("# Each entry: (phys, pos, fmt_code, width)")
    a("")
    a("FP_REG_DATA: dict[str, tuple[int, int, int, int]] = {")
    for reg in isa["fp_registers"]:
        a(f'    "{reg["name"]}": ({reg["phys"]}, {reg["pos"]}, {reg["fmt"]}, {reg["width"]}),')
    a("}")
    a("")

    # MNEMONIC_ALIASES
    a("# ── Mnemonic aliases ─────────────────────────────────────────────────")
    a("")
    a("MNEMONIC_ALIASES: dict[str, str] = {")
    for alias, canonical in isa["mnemonic_aliases"].items():
        a(f'    "{alias}": "{canonical}",')
    a("}")
    a("")

    return "\n".join(lines)


# ── JS generator ──────────────────────────────────────────────────────────────


def _gen_js(isa: dict) -> str:
    lines: list[str] = []
    a = lines.append

    a("// AUTO-GENERATED by isa/codegen.py — do not edit directly.")
    a("// Source of truth: spec/isa.json")
    a("")

    # Op object
    a("export const Op = Object.freeze({")
    groups = [
        ("Core (0–97)", isa["instructions"]),
        ("FP (128–162)", isa["instructions_fp"]),
        ("VU (163–183)", isa["instructions_vu"]),
    ]
    for group_label, instrs in groups:
        a(f"    // {group_label}")
        for instr in instrs:
            a(f"    {instr['op']}: {instr['opcode']},")
        a("")
    a("});")
    a("")

    # ISA_DATA
    a("// ── Instruction data ─────────────────────────────────────────────────")
    a("// Each entry: [op_name, opcode, mnemonic, operands, cost, formatDep]")
    a("")

    for var, key in [
        ("ISA_DATA", "instructions"),
        ("ISA_FP_DATA", "instructions_fp"),
        ("ISA_VU_DATA", "instructions_vu"),
    ]:
        a(f"export const {var} = [")
        for instr in isa[key]:
            fd = "true" if instr.get("format_dep", False) else "false"
            ops = _repr_list(instr["operands"])
            a(f'    ["{instr["op"]}", {instr["opcode"]}, "{instr["mnemonic"]}", {ops}, {instr["cost"]}, {fd}],')
        a("];")
        a("")

    # FP_REG_DATA
    a("// ── FP register data ─────────────────────────────────────────────────")
    a("// Each entry: [phys, pos, fmt_code, width]")
    a("")
    a("export const FP_REG_DATA = Object.freeze({")
    for reg in isa["fp_registers"]:
        a(f"    {reg['name']}: [{reg['phys']}, {reg['pos']}, {reg['fmt']}, {reg['width']}],")
    a("});")
    a("")

    # MNEMONIC_ALIASES
    a("// ── Mnemonic aliases ─────────────────────────────────────────────────")
    a("")
    a("export const MNEMONIC_ALIASES = Object.freeze({")
    for alias, canonical in isa["mnemonic_aliases"].items():
        a(f'    {alias}: "{canonical}",')
    a("});")
    a("")

    return "\n".join(lines)


# ── VSCode grammar updater ────────────────────────────────────────────────────

_FP_CONTROL = {"FSTAT", "FCFG", "FSCFG", "FCLR"}


def _collect_mnemonics(isa: dict) -> dict[str, list[str]]:
    """Return ordered unique mnemonics per vscode category."""
    seen: dict[str, list[str]] = {k: [] for k in ("core", "fp", "fp_control", "vu_sync", "vu_async")}

    def _add(cat: str, mn: str) -> None:
        if mn not in seen[cat]:
            seen[cat].append(mn)

    for instr in isa["instructions"]:
        _add("core", instr["mnemonic"])

    for instr in isa["instructions_fp"]:
        cat = "fp_control" if instr["mnemonic"] in _FP_CONTROL else "fp"
        _add(cat, instr["mnemonic"])

    for instr in isa["instructions_vu"]:
        cat = "vu_sync" if instr.get("sync", False) else "vu_async"
        _add(cat, instr["mnemonic"])

    return seen


def _update_vscode(isa: dict, grammar_path: Path) -> str:
    grammar = json.loads(grammar_path.read_text())
    repo = grammar["repository"]
    mn = _collect_mnemonics(isa)

    def _alt(names: list[str]) -> str:
        return "|".join(names)

    # core mnemonics
    repo["mnemonic"]["match"] = f"(?i)\\\\b({_alt(mn['core'])})\\\\b"

    # fp-instruction
    fp_mn = _alt(mn["fp"])
    # keep the format suffix part from original
    orig_fp = repo["fp-instruction"]["match"]
    suffix_part = re.search(r"\((?:\\..*?)\)", orig_fp)
    fp_suffix = suffix_part.group(0) if suffix_part else r"((?:\.(?:E\d+M\d+|BF|O[23]|N[12]|[FH]))+)"
    repo["fp-instruction"]["match"] = f"(?i)\\\\b({fp_mn}){fp_suffix}\\\\b"

    # fp-control
    repo["fp-control"]["match"] = f"(?i)\\\\b({_alt(mn['fp_control'])})\\\\b"

    # vu-instruction (async)
    vu_mn = _alt(mn["vu_async"])
    orig_vu = repo["vu-instruction"]["match"]
    vu_suffix_part = re.search(r"\((?:\\..*?)\)", orig_vu)
    vu_suffix = (
        vu_suffix_part.group(0) if vu_suffix_part else r"((?:\.(?:BF|O[23]|[FHUI]|VV|VS|VI|R|EQ|NE|LT|LE|GT|GE))+)"
    )
    repo["vu-instruction"]["match"] = f"(?i)\\\\b({vu_mn}){vu_suffix}\\\\b"

    # vu-sync
    repo["vu-sync"]["match"] = f"(?i)\\\\b({_alt(mn['vu_sync'])})\\\\b"

    return json.dumps(grammar, indent=2, ensure_ascii=False) + "\n"


# ── main ──────────────────────────────────────────────────────────────────────


def _write_if_changed(path: Path, content: str, check: bool) -> bool:
    """Write content to path. In check mode, just report if it differs."""
    existing = path.read_text() if path.exists() else ""
    if existing == content:
        return False
    if check:
        print(f"  STALE: {path.relative_to(_REPO)}")
        return True
    path.write_text(content)
    print(f"  wrote: {path.relative_to(_REPO)}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if any output is out of date (no writes)")
    args = parser.parse_args(argv)

    isa = json.loads(_JSON.read_text())

    py_content = _gen_py(isa)
    js_content = _gen_js(isa)
    vscode_content = _update_vscode(isa, _VSCODE_OUT)

    changed = False
    changed |= _write_if_changed(_PY_OUT, py_content, args.check)
    changed |= _write_if_changed(_JS_OUT, js_content, args.check)
    changed |= _write_if_changed(_VSCODE_OUT, vscode_content, args.check)

    if args.check and changed:
        print("Run `python isa/codegen.py` to regenerate.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
